# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-15 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testweb_01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_banner_type',
            new_name='banner_type',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_summary',
        ),
        migrations.AddField(
            model_name='project',
            name='summary',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
    ]
