# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-16 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testweb_01', '0002_auto_20160815_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default=123, max_length=200, verbose_name='标题'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='banner_type',
            field=models.CharField(choices=[('BANNER_LEFT', 'bnr_lft'), ('BANNER_RIGHT_GRID1', 'bnr_rht_grid1'), ('BANNER_RIGHT_GRID2', 'bnr_rht_grid2'), ('BANNER_RIGHT_GRID3', 'bnr_rht_grid3'), ('BANNER_RIGHT_GRID4', 'bnr_rht_grid4'), ('NONE', 'none')], default='NONE', max_length=200, verbose_name='是否图片栏'),
        ),
        migrations.AlterField(
            model_name='project',
            name='content',
            field=models.TextField(help_text='A content for this thing', verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.CharField(max_length=200, verbose_name='简介'),
        ),
    ]
