# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-18 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testweb_01', '0003_auto_20160816_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='标题')),
                ('summary', models.CharField(max_length=200, verbose_name='简介')),
                ('content', models.TextField(help_text='A content for this thing', verbose_name='正文')),
            ],
        ),
    ]
