# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-18 02:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testweb_01', '0004_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
    ]
