# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-18 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testweb_01', '0005_auto_20160818_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='background_image',
            field=models.ImageField(default=123, upload_to='g0.jpg'),
            preserve_default=False,
        ),
    ]
