# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-19 03:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testweb_01', '0007_auto_20160819_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
